language: node_js
node_js:
- node
script:
- printf 'configs/\nsrc/\n.npmignore\n.travis.yml\nCHANGELOG.md\nGruntfile.js\nbower.json\nLICENSE-MIT\npackage.json\nnode_modules/\n.gitignore\ndeployed*' > .gitignore
- printf '.npmignore\n.travis.yml\nCNAME' > .npmignore
- printf 'photoroller.martinmetodiev.com' > CNAME
branches:
  only:
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
deploy:
- provider: npm
  email: metodiev.martin@gmail.com
  api_key:
    secure: CaIDFOl/VXpzXoSmKVJKSkYW8s7uildKvCdIZAlR4EcTf1PMc6mlXH1FoOEK0JJmfPqT/0dBOvKp0TVb5TTyigI23xWhpqWcN89g7cd5OeS1mQtm4mMNbFGqZ7xUjQJcQiwcSPWs3d8wDlf3FtBy25kLXj6Y5DQLRn7TV5NGUtEDp3ormlDXrNVT7z23I4/Y25Rkp+HwgWZQHFDL6J2/++ise9x8xi7dN66MziEQ+5JvogNm5m3t4g4IjW4VPeyjD7hbUAohbJhGlEc1B6WpyTTJM0wTnr3J4sKQuUKqodilOCmKRfsbMnH2lqbV+iKHWXq/jrYVkGeMUwd3nPCJaytqU8enbYsefQ0DN3XkCVEKTg2lTaWUVnFDsRIGouETsNk2T/w3PNAMA2ss8eNJbQAEm9zKaqsbss7gLiYurHXkFI7LwvF8ce6bhH6pVX5CQRai1Aqh0jOtEhYMvczZzdCcgJva0mwLxdaLcMwxHqaTRM2AYk60ruTPC7CCJIKRJDoRG5B+bmx+lY8bzozRv4Phj0dqePZSH0yabh5Jkq+ABhJxpU3iXFslgOFdEukBqxEZGyM0YG3el/KX8Yyld1s1UJ8ORLG5vrqfx/rA8gjFFRY68N97gQnVKWkzY4ZnTgIJlT9qiwOE52vXDApJQLFXCtAaLKgg2md7PsWiMkI=
  on:
    tags: true
- provider: pages
  skip_cleanup: true
  github_token:
    secure: I3JH8CfA/KC+Mp4xzMNIWCjnTrtk/9ZEdW/jjbPGPWb2WEJbzAhpjRLAtLeAg3IJbOsh5b6h8T79FDUYn1n1Gm8nEzBkZuYz9WNyYDGcgYnEkYoJ1K6VZUnNe9Qx0n57KTNx7rwJEFwGnjLAdL+lX/qz9JfWUfAdTv5FBHtCFugPJ+s5aXo8AWusGhHoguB1mD7ayUu7MaH3OxL1+0Jok5OkkEiIZZodRGYGwx3gUNZB1fE5hr1Fp/xUV0i1FVSI2vBX97WTgdkh/W3bkbiBBR7PL4LvH6XZmvDJAL4NK3jMz7owNe7puqUhe8XWwcXWdj2XKQdiH5D+eT5ysl1ZjxbEVC4NOy9qMYlHWr2JlD344WAP93Y0rHKYTt1Zo+F7FsLsNZeo3bmQ9tYdY8ytQ4bejCza3ldbqCE0QIfSFSQI/uiAogOFOKu0wCgPEpEpxu9ElIGDydMfzeCCUZT2vhpFJEjGiKy0X6DZhheGA8B/5dCO5dnG/ss8gThg2PZtM+iwL6XF2bgMfWBW5Gzf7nVrQ8V81HjiG9EfvnFHorhGuUqqahwH8t1wQvYzYkswpb4vFP5aOSNhyXSFizDzLl2Y5dvVYPLzB0fVy2iw62lZuIjWI6ewWDrdc4xv5I0FyyaWDDMnkBM7ebVBa4DPbhYkP5/6+vL9cg3g6A0aGlI=
  on:
    tags: true
- provider: releases
  api_key:
    secure: I3JH8CfA/KC+Mp4xzMNIWCjnTrtk/9ZEdW/jjbPGPWb2WEJbzAhpjRLAtLeAg3IJbOsh5b6h8T79FDUYn1n1Gm8nEzBkZuYz9WNyYDGcgYnEkYoJ1K6VZUnNe9Qx0n57KTNx7rwJEFwGnjLAdL+lX/qz9JfWUfAdTv5FBHtCFugPJ+s5aXo8AWusGhHoguB1mD7ayUu7MaH3OxL1+0Jok5OkkEiIZZodRGYGwx3gUNZB1fE5hr1Fp/xUV0i1FVSI2vBX97WTgdkh/W3bkbiBBR7PL4LvH6XZmvDJAL4NK3jMz7owNe7puqUhe8XWwcXWdj2XKQdiH5D+eT5ysl1ZjxbEVC4NOy9qMYlHWr2JlD344WAP93Y0rHKYTt1Zo+F7FsLsNZeo3bmQ9tYdY8ytQ4bejCza3ldbqCE0QIfSFSQI/uiAogOFOKu0wCgPEpEpxu9ElIGDydMfzeCCUZT2vhpFJEjGiKy0X6DZhheGA8B/5dCO5dnG/ss8gThg2PZtM+iwL6XF2bgMfWBW5Gzf7nVrQ8V81HjiG9EfvnFHorhGuUqqahwH8t1wQvYzYkswpb4vFP5aOSNhyXSFizDzLl2Y5dvVYPLzB0fVy2iw62lZuIjWI6ewWDrdc4xv5I0FyyaWDDMnkBM7ebVBa4DPbhYkP5/6+vL9cg3g6A0aGlI=
  skip_cleanup: true
  on:
    tags: true
