language: node_js
node_js:
- node
script: bash ./deploy.sh
env:
  global:
  - ENCRYPTION_LABEL: 07f299903355
  - COMMIT_AUTHOR_EMAIL: metodiev.martin@gmail.com
branches:
  only:
  - "/v\\d+\\.\\d+\\.\\d+/"
deploy:
  provider: npm
  email: metodiev.martin@gmail.com
  api_key: # …0ae8ec4a
    secure: S0wqDgGmNBhCSpc+E+8UYMEVEOmTMG+D1EG44NFm8CcQFPdg6M3BwbEo73/rStQkuBG7V46oYl8iLLeP/VINkZnXxc36VGV2xupRHcL16Z83SnaXBhktjKp0Gm2vWHLGThgyVYc2C4f+0XGoxRPQJbA25h9Y83FAjfy9/eMMy9BGpzjEIjgCkJDZAWim3dfI9ZbBhdWUkMhvNrHGWorLHzbNEfVOKDxdWeWPdsNgY74J7snOheP8WsGWzAeF9/HxbGxrAsjMu8oD1n4IJZ02FLDbTWPkvDQBMrFIfMR+9Wy37IMl37MGCSvNeAwerOpgI4ZL39ctaYlYCsg2P3XKnqLyn/3lts2owH4+i3NKhgPD4ixfMOEToBVZwZaRYIE906ilcBFjW8IQjNcxzsBU99SgmifFNBUjqHji0moEeagrO97CLIc3VSulgztjVZrP/t4uwHe5jOnUKZZ2SVB5dvMAA+PN3yFaxc1QpjYK1yX1Wvm6ZDhc8Q3VB7nOErvn5QBCFoK9lqBbpJ5tubPC3k8VpheoaEJBzCOofufgtPA1mxIqBBnBiLuVU8LF0zHNaKlgmEgqu+2Cj5LxIyTPKWy1IHjtdc3BrpRhGCrmJzDEp+dgg0P8joCln/yn7svfApwfYNmnIzyWrvrfVWD/Iq9Y3K7QF3n7nhGiw6A9Y4E=
  on:
    tags: true
    all_branches: true
