language: node_js
node_js:
- 7.8
script:
- printf 'configs/\nsrc/\n.npmignore\n.travis.yml\nCHANGELOG.md\nGruntfile.js\nbower.json\nLICENSE-MIT\npackage.json\nnode_modules/\n.gitignore\ndeployed*' > .gitignore
- printf '.npmignore\n.travis.yml\nCNAME' > .npmignore
- printf 'photoroller.metodiev.dev' > CNAME
branches:
  only:
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
deploy:
- provider: npm
  email: metodiev.martin@gmail.com
  api_key:
    secure: CaIDFOl/VXpzXoSmKVJKSkYW8s7uildKvCdIZAlR4EcTf1PMc6mlXH1FoOEK0JJmfPqT/0dBOvKp0TVb5TTyigI23xWhpqWcN89g7cd5OeS1mQtm4mMNbFGqZ7xUjQJcQiwcSPWs3d8wDlf3FtBy25kLXj6Y5DQLRn7TV5NGUtEDp3ormlDXrNVT7z23I4/Y25Rkp+HwgWZQHFDL6J2/++ise9x8xi7dN66MziEQ+5JvogNm5m3t4g4IjW4VPeyjD7hbUAohbJhGlEc1B6WpyTTJM0wTnr3J4sKQuUKqodilOCmKRfsbMnH2lqbV+iKHWXq/jrYVkGeMUwd3nPCJaytqU8enbYsefQ0DN3XkCVEKTg2lTaWUVnFDsRIGouETsNk2T/w3PNAMA2ss8eNJbQAEm9zKaqsbss7gLiYurHXkFI7LwvF8ce6bhH6pVX5CQRai1Aqh0jOtEhYMvczZzdCcgJva0mwLxdaLcMwxHqaTRM2AYk60ruTPC7CCJIKRJDoRG5B+bmx+lY8bzozRv4Phj0dqePZSH0yabh5Jkq+ABhJxpU3iXFslgOFdEukBqxEZGyM0YG3el/KX8Yyld1s1UJ8ORLG5vrqfx/rA8gjFFRY68N97gQnVKWkzY4ZnTgIJlT9qiwOE52vXDApJQLFXCtAaLKgg2md7PsWiMkI=
  on:
    tags: true
- provider: pages
  skip_cleanup: true
  github_token:
    secure: fB6ETGQh1EYAQtNp20gPQa1jL0TUVrBckJl5qO06ea1daDwkEDDPgfEqn/2M8faS18wLWRJvhVzkzWVOLnV3eIBb4X3hRwMqj1seOn748SsGiWbhEeSnx6R1fU73TQoAuPmk5T0vWAVwgOXu/DmEU7pfunU4zhGIZueyq74sxyMArhhc63NAUjDyJYIxuY/JwJ0EWdvLVRz5AbQNPKqX9RujwWWS3dYJYy9BSdAwwuq6awuY+d79eJS0BG5E7hEoT01IozY1xiRo0CDUohrWdehZ9IuPOotcYps0yuaw7ACKuphLrJpluevNmgtxuS3E/zaBPpt6ic+PiUQTtMoromt67DppZV4ahCpNxEtRe+rpqVX13WXy9e72XU+kmcn8gU0bLVDJl7vucuczc5MPz3k8D/EaccZHLMwVOE275wN5QCGUvM+U+trJ3Lh4j8hS+OxvyMBT6Z8j213Ph0zYbuGdgBcY8Tybe8VEhBJfdd35+nFuVrCDVRJi8V6/RP6EZ6/HvKKEsY1f8L9pUgz+GVOEMsWesDxbuBQb3YzBhJowKTvolvWtVEmD7wIC1Cc+mrnj1xQdu2dqA6kYKvZ9oIjZGEgagiAcN1aKYsMEhFhtkEgboUR0IB3CEbJyU76D+TnA70aFoAr5t2hAzI/6h3E6K5iS+HX1NwoSjAHs3EI=
  on:
    tags: true
- provider: releases
  api_key:
    secure: fB6ETGQh1EYAQtNp20gPQa1jL0TUVrBckJl5qO06ea1daDwkEDDPgfEqn/2M8faS18wLWRJvhVzkzWVOLnV3eIBb4X3hRwMqj1seOn748SsGiWbhEeSnx6R1fU73TQoAuPmk5T0vWAVwgOXu/DmEU7pfunU4zhGIZueyq74sxyMArhhc63NAUjDyJYIxuY/JwJ0EWdvLVRz5AbQNPKqX9RujwWWS3dYJYy9BSdAwwuq6awuY+d79eJS0BG5E7hEoT01IozY1xiRo0CDUohrWdehZ9IuPOotcYps0yuaw7ACKuphLrJpluevNmgtxuS3E/zaBPpt6ic+PiUQTtMoromt67DppZV4ahCpNxEtRe+rpqVX13WXy9e72XU+kmcn8gU0bLVDJl7vucuczc5MPz3k8D/EaccZHLMwVOE275wN5QCGUvM+U+trJ3Lh4j8hS+OxvyMBT6Z8j213Ph0zYbuGdgBcY8Tybe8VEhBJfdd35+nFuVrCDVRJi8V6/RP6EZ6/HvKKEsY1f8L9pUgz+GVOEMsWesDxbuBQb3YzBhJowKTvolvWtVEmD7wIC1Cc+mrnj1xQdu2dqA6kYKvZ9oIjZGEgagiAcN1aKYsMEhFhtkEgboUR0IB3CEbJyU76D+TnA70aFoAr5t2hAzI/6h3E6K5iS+HX1NwoSjAHs3EI=
  skip_cleanup: true
  on:
    tags: true
